# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

steps:
  
- script: carthage bootstrap --verbose --platform ios --color auto --cache-builds
  displayName: 'carthage bootstrap'

- script: $(which npm) install
  displayName: 'npm install'

- script: /usr/local/bin/pod install
  displayName: 'pod install'

- task: CocoaPods@0
  displayName: 'pod install using the CocoaPods task with defaults'

- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'Fennec'
    sdk: 'iphonesimulator'
    xcWorkspacePath: '**/*Client.xcworkspace'
    xcodeVersion: 9 # Options: 8, 9, default, specifyPath
    
